# Generated by Django 6.1 on 2026-08-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AlterField(
            model_name='advantage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='core.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фотография тура',
                'verbose_name_plural': 'Фотографии тура',
                'ordering': ['order'],
            },
        ),
    ]
