# Generated by Django 6.0.8 on 2026-08-24 08:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tour_image_alter_advantage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='program',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Программа по дням'),
        ),
    ]
